[server]
headless = true
address = "0.0.0.0"
port = 5000
folderWatchBlacklist = [".*", "*/reports/*", "*/temp_*/*"]

[browser]
gatherUsageStats = false
serverAddress = "localhost"

[theme]
primaryColor = "#4267B2"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F0F2F5"
textColor = "#1E293B"
font = "sans serif"

[ui]
hideTopBar = true

[client]
showErrorDetails = false
toolbarMode = "minimal"

[global]
developmentMode = false

[runner]
fastReruns = true

[logger]
level = "error"